### ISSUE TITLE
Is master reelection supported?

### ISSUE THREAD

**Issue by synhaptein** [richardwilly98/elasticsearch-river-mongodb#534]
Is it possible that a master reelection (master failed, a new master is elected and then the old master reconnect as a slave) is not supported by the plugin? It marked some of the river as IMPORT_FAILED and never resync? I try to restart it in the GUI... STOP and START... but nothing it stay "START" but doesn't sync :\ Any idea?

**Comment by kdkeck** [comment]
The river doesn't necessarily run on the master; it's probably gotten 
stuck running on one of the other nodes.  Because we've also seen this 
kind of stalled river too, and don't want to bring down nodes holding 
large indexes just to restart it, we're in the process of updating our 
cluster to include a node that's excluded from shard allocation, to just 
run the river(s), and configuring all our other nodes to not run any 
rivers.  When we're done, we should be able to forcibly restart the 
river by restarting the river node, without disrupting the nodes hosting 
shards.
